Δημιουργία σελίδας για το ωρολόγιο πρόγραμμα
ioniodi/site-gr pull request #141
Opened 2020-05-26 12:03 UTC by AsteriosP

### Σχετικό Issue
closes #114 

### Σχετικό PR στο minimal-ionio
https://github.com/ioniodi/minimal-ionio/pull/31

### Προτεινόμενες Αλλαγές
 - τα entry της κας Χριστοπούλου που βρίσκονται στο `_data/authors.yml` διότι ήταν ανάποδα το `name`

 - Δημιουργία ενός καινούργιου collection με όνομα `timetables` για την αποθήκευση των Ωρολογίων Προγραμμάτων  

 - Προσθήκη της αρχικής σελίδας του καινούργιου collection στο navigation bar 

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2020-05-28 08:56 UTC, p15zerv requested changes
Αρκετά κομψή η υλοποίηση της δομής, μπράβο!

Κάτι σημαντικό που θα δημιουργήσει πρόβλημα είναι πως με το #135 μετακινείται ο φάκελος `pages` εκτός του `all_collections/`. Οπότε, εφόσον το #135 προηγείται χρονικά του τωρινού, μάλλον εδώ θα πρέπει να γίνει η αλλαγή για το `timetables.md`

Δεν έχω να σχολιάσω κάτι αρνητικό για την υλοποίηση, πέρα από το να θίξω κάποια ζητήματα ευχρηστίας. Το πρόγραμμα είναι κάτι που θα χρειαστεί να αλλάξει αρκετές φορές κατά τη διάρκεια του εξαμήνου, ειδικά αφού μιλάμε για ένα πρόγραμμα ανά εξάμηνο. Η συμπλήρωση της συγκεκριμένης δομής θα ήταν αρκετά χρονοβόρα και ίσως αδύνατη για ένα τελικό χρήστη (όπως γραμματεία). Λογικά, η γραμματεία διαθέτει ήδη τα πρόγραμματα σε κάποιο άρχείο τύπου docx ή pdf, οπότε μήπως θα ήταν εφικτό μακροπρόθεσμα να δούμε αν μπορούν να εμφανιστούν απευθείας τέτοιου είδους αρχεία στο site;

Σκέψεις για μελλοντικές βελτιώσεις. Όπως και να έχει, φαίνεται ότι έχει δουλευτεί αρκετά το συγκεκριμένο PR και είναι μια καλή αρχή! Μόλις μετακινηθεί το page εκτός του all collections είναι approve από εμένα, εκτός κι αν παρατηρηθεί άλλο πρόβλημα από άλλους.

2020-05-28 21:33 UTC, Spirosvw commented
Μπράβο @AsteriosP  πολύ καλή δουλειά. Θα συμφωνήσω όμως με τον @p15zerv πως ίσως θα ηταν πιο εύχρηστο για την γραμματεία να μπορεί να ανεβάσει ένα αρχείο τύπου pdf ή docx (πιθανό νέο issue?). Παρόλα αυτά, η υλοποίηση αυτή φαίνεται πολύ καλή οπότε θα προχωρήσω και εγώ στο approve όταν μεταφέρεις το timetables.md στο pages του theme.

2020-05-29 12:49 UTC, KonstantinosG commented
Πολύ καλή η υλοποίηση @AsteriosP! Είναι πολύ εύχρηστος ο πίνακας καθώς έχει highlight όταν κάνεις hover με τον κέρσορα. Φαίνεται κατευθείαν δηλαδή η ώρα των μαθημάτων ειδικότερα για αυτά που βρίσκονται προς τις τελευταίες στήλες. Ας γίνει και το τελευταίο βήμα που ανέφεραν και οι υπόλοιποι (@Spirosvw @p15zerv) για να προχωρήσει.

2020-05-29 13:27 UTC, AsteriosP commented
@p15zerv, είναι έτοιμο

2020-05-30 11:21 UTC, p15zerv reviewed
Είσαι σίγουρος ότι εμφανίζεται σωστά μετά τις αλλαγές το `_pages/timetables.md`; Αν δεις το #135, σε όλες τις σελίδες στο `_pages` υπάρχει permalink ώστε να προτιμάται αυτή η σελίδα κι όχι ο φάκελος στα collections με το ίδιο όνομα. Έχει ανανεωθεί το demo?

2020-05-30 13:36 UTC, provopoulos requested changes
Πολύ κομψή υλοποίηση ωστόσο όπως αναφέρουν και παραπάνω ίσως υπάρχει κάποιο θέμα με το DEMO γιατί μου εμφανίζει αρχικά πως η σελίδα δεν βρέθηκε και ύστερα να επιλέξω προγράμματα εξαμήνων από τα προτεινόμενα αποτελέσματα αναζήτησης.
Μια μικρή λεπτομέρεια, έχει ξεφύγει η ορθογραφία στο μάθημα «Προγραμματισμός Υπολογιστών» της Πέμπτης στην αίθουσα διδασκαλίας.

2020-05-30 13:42 UTC, provopoulos commented
@p15zerv 
Κατά λάθος ζήτησα επανεξέταση του αιτήματός σου για αλλαγές ενώ έψαχνα για μια άλλη λειτουργία. Υποθέτω πως μπορείς να το ενημερώσεις ξανά μόλις πραγματοποιηθούν οι αλλαγές που αναφέρθηκαν.

2020-05-30 22:34 UTC, p15zerv approved these changes
ΟΚ μετά τη μεταφορά της σελίδας και προσθήκη του permalink.

Good job!

2020-06-01 16:19 UTC, epidrome commented
@AsteriosP 
βγάζει σύγκρουση σε ένα αρχείο, ίσως θα μπορούσε να αφαιρεθεί και να μπει σε επόμενο χρόνο;

πάντως έχει ενδιαφέρον γιατί βλέπετε στην πράξη πως οι αλλαγές σε πολλά αρχεία σε ένα συνεργατικό έργο είναι η συνταγή για προβλήματα..

@Spirosvw @KonstantinosG @provopoulos @andreanastil 
 σας παρακαλώ για την άμεση αξιολόγηση για να προχωρήσουμε σε ριζική αναμόρφωση του αποθετηρίου

2020-06-01 16:49 UTC, epidrome commented on all_collections/_timetables/sem_b.md
> +    location: "Αμφηθέατρο 1"
Αμφιθέατρο

μια ιδέα για άνοιγμα νέου θέματος βελτίωσης θα ήταν οι τοποθεσίες να είναι παράμετροι-κλειδιά σε ξένο πίνακα, πχ TAB-1 να δείχνει προς μια δομή η οποία θα περιέχει επιπλέον δεδομένα, όπως το όνομα και την γεωγραφική τοποθεσία

2020-06-01 17:21 UTC, provopoulos commented
@epidrome 
> Βγάζει σύγκρουση σε ένα αρχείο, ίσως θα μπορούσε να αφαιρεθεί και να μπει σε επόμενο χρόνο;

Νομίζω η επίλυση της συγκεκριμένης σύγκρουσης είναι εύκολη (αν καταλαβαίνω καλά) ωστόσο καλύτερα να το ελέγξει ο @AsteriosP για να είμαστε σίγουροι πριν συνεχίσουμε.

Σε κάθε περίπτωση δεν παρουσιάζεται μήνυμα λάθους 404 στο DEMO με τις τελευταίες αλλαγές όμως τα ορθογραφικά λάθη παραμένουν.

2020-06-01 22:39 UTC, p15zerv requested changes
@epidrome 
> βγάζει σύγκρουση σε ένα αρχείο, ίσως θα μπορούσε να αφαιρεθεί και να μπει σε επόμενο χρόνο;

Όντως, νομίζω με το #144 δημιουργήθηκε... Πρέπει να είναι πράγματι μικρή η αλλαγή, ας περαστεί από τον @AsteriosP πριν προχωρήσουμε...

2020-06-02 16:20 UTC, p15zerv approved these changes
Αν έχει ανανεωθεί το demo, οι αλλαγές πρέπει να είναι οκ πλέον!

2020-06-02 16:33 UTC, provopoulos approved these changes
No more conflicts and demo seems to be working as expected. LGTM!

2020-06-02 16:51 UTC, merged

2020-06-02 16:53 UTC, andreanastil approved these changes