Συντομεύσεις πλοήγησης με την οργάνωση και τις βασικές σελίδες
ioniodi/site-gr pull request #93
Opened 2020-04-05 20:34 UTC by AsteriosP

### Σχετικό Issue
closes #67 

[οι προτεινόμενες αλλαγές στο netlify](https://gifted-lumiere-2ce1cb.netlify.com/)

### Προτεινόμενες Αλλαγές
-- Έγινε δημιουργία νέου αρχείου `shortcuts.yml` στον φάκελο που αναφέρεται στο αντίστοιχο [issue](https://github.com/ioniodi/site-gr/issues/67) 
-- Για την ορθή λειτουργία των αλλαγών του pull request πρέπει να γίνει αποδοχή του αντίστοιχου [pull request]() στο minimal-ionio 

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2020-04-08 18:31 UTC, NikosAvg approved these changes

2020-04-08 18:31 UTC, epidrome requested changes
στο προσωπικό νομίζω πως είναι σημαντικότερο να έχουμε "θεσμούς" (π.χ., πρόεδρος, γραμματεία, κτλ) παρά πρόσωπα.

στο αντίστοιχο θέμα έχω ανεβάσει αρχείο με σελίδες όπως προκύπτουν από το google search

2020-04-08 21:32 UTC, ghost requested changes
Πιστεύω πολύ απλή λύση για να λυθεί το πρόβλημα. Μια αλλαγή στο name tag φαίνεται να είναι.

Για την γραμματεία θα χρειαστεί να έχουμε ειδική σελίδα στο site ώστε να κατευθύνουμε εκεί αλλιώς μπορούμε να το προσθέσουμε σαν εξωτερικό link στο http://events.di.ionio.gr/diold/content/contact/contact-details/ η κάπου παρόμοια.

2020-04-08 21:32 UTC, constantinexisc commented on _data/shortcuts.yml
> +      - name: Βασίλειος Χρυσικόπουλος
Ίσως να αλλάξει σε 'Πρύτανης', το ίδιο και για τον πρόεδρο κ Βλάμο.

2020-04-09 13:30 UTC, epidrome commented
@NikosAvg αν θες να το δεις άλλη μια φορά σε συνάρτηση με τις αξιολογήσεις που έχουν γίνει και να γράψεις μια (μικρή) αξιολόγηση

2020-04-09 14:27 UTC, epidrome commented
μάλλον κατά λάθος μπήκε και ένα κονφιγκ στο πουλ

2020-04-09 17:24 UTC, merged

2020-04-09 17:26 UTC, GIANNIS-AGGELIS commented
@AsteriosP Και τα δυο pull-request έγιναν merge

2020-04-09 17:40 UTC, constantinexisc commented
test for reopen

2020-04-09 17:53 UTC, GIANNIS-AGGELIS commented
@AsteriosP  , @epidrome  Πρέπει να ξανά γίνει το pull request με της απαραίτητες αλλαγές στο απαραίτητα αρχεία ώστε να μην εμφανίζονται τα δυο footers. Έχω κάνει απαραίτητα τα reverts για να έρθει στην προηγούμενη κατάσταση #100.

2020-04-13 08:41 UTC, epidrome commented
@GIANNIS-AGGELIS 
γιατί έγινε δεκτό αφού υπήρχαν αρνητικές αξιολογήσεις-σχόλια???

2020-04-14 18:48 UTC, GIANNIS-AGGELIS commented
@epidrome 
Δεν είχα καταλάβει πια είναι τα review και την διαδικασία , τώρα που είδα πως λειτουργούν τα review και οι αλλαγές πιστεύω δεν θα έχουμε πρόβλημα στο μέλλον.
Έξαλλου να δεν δει ο καθένας πως λειτουργεί στην πράξη δεν θα μάθει.