Dynaminc data
ioniodi/site-gr pull request #94
Opened 2020-04-06 19:54 UTC by Spirosvw

### Σχετικό Issue
closes #78 

### Προτεινόμενες Αλλαγές
-- Αλλαγή 1
-Δημιουργία φακέλου _includes και dynamic.html για την υλοποίηση της δυναμικής αλλαγής του περιεχομένου στην αρχική σελίδα

-- Αλλαγή 2
-Επεξεργασία του αρχείου index.html για την χρήση του dynamic.html για την εμφάνιση δυναμικού περιεχομένου

Ενδεικτικό link: https://sharp-borg-3fc7ea.netlify.com/

### Υπενθυμίσεις
- [ ] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [ ] Έχω δημιουργήσει branch για τις αλλαγές

2020-04-08 21:21 UTC, ghost requested changes
Υπάρχει ένα μικρό regression που μπορεί να αλλάξει εύκολα.

2020-04-08 21:21 UTC, constantinexisc commented on index.html
> +  cta_url: "http://di.ionio.gr/wp-content/uploads/2016/09/OS_2016-2017-final.pdf"
Γιατί υπάρχει αυτή η αλλαγή εδώ περα που είναι fallback σε πιο παλιό link? Νομίζω είναι λάθος που ξέφυγε.

2020-04-09 10:26 UTC, Spirosvw commented on index.html
> +  cta_url: "http://di.ionio.gr/wp-content/uploads/2016/09/OS_2016-2017-final.pdf"
Πρεπει να ειναι επειδη χρησιμοποιησα παλιο version του html

2020-04-09 10:29 UTC, Spirosvw commented
> Υπάρχει ένα μικρό regression που μπορεί να αλλάξει εύκολα.

Χρησιμοποιήσα παλιότερη version του html. Διόρθωσα το λάθος

2020-04-09 12:39 UTC, ghost approved these changes

2020-04-13 13:47 UTC, epidrome commented
μπράβο, φαίνεται ωραιά
το μόνο σημαντικό σχόλιο που έχω είναι
ότι το ινκλουντ ταιριάζει καλύτερα στο θέμα
για την ώρα, αν συμφωνούν και οι αξιολογητές
ας το κάνουμε δεκτό και μετά το διαγράφεις-στέλνεις
στο μινιμαλ-ιονιο

@p15zerv @GIANNIS-AGGELIS 
αν θέλετε να το δείτε με προτεραιότητα 
ώστε να προχωρήσει ο @Spirosvw στο
επόμενο παραδοτέο του

2020-04-13 18:50 UTC, p15zerv approved these changes
Κι εμένα μια χαρά μου φαίνεται. Συμφωνώ ότι το dynamic.html μάλλον είναι καλύτερα να πάει στο theme, αλλά για τώρα μπορεί να γίνει δεκτό κι ας αλλάξει αργότερα.

2020-04-14 18:38 UTC, GIANNIS-AGGELIS approved these changes
Μια χαρά μου φαίνονται οι αλλαγές που έκανε ο @Spirosvw . Θα συμφωνήσω με τον @p15zerv  για τι μεταφορά του αρχείου αργότερα.

2020-04-14 20:25 UTC, merged

2020-04-16 13:02 UTC, epidrome commented
@constantinexisc @Spirosvw 

ούτε τοπικά, ούτε στο λινκ του αποθετηρίου 

δεν βλέπω τις δυναμικές αναρτήσεις???

2020-04-16 13:48 UTC, constantinexisc commented
@epidrome

Να εξηγήσω, η δυναμικότητα έιναι βασισμένη στη μεταβλητή site.time, αφού το jekyll είναι static site generator δεν μπορεί να έχει κάποιο άλλο είδος δυναμικότητας ή τυχαιότητας αφότου έχει "χτισει" τις σελίδες και τις κάνει serve.

Κάθε φορά που θα γίνεται καινούργιο jekyll serve το site.time θα ενημερώνεται και θα δίνει κάποια άλλα post στην αρχική.

2020-04-16 15:20 UTC, epidrome commented
@constantinexisc 
[ευχαριστώ! γνωρίζω πως δουλεύει, αφού η υλοποίηση βασίζεται στην δικιά μου από το σαιτ του βιβλίου](https://github.com/ioniodi/site-gr/issues/78#issuecomment-604404942)

η απορία ήταν δικό μου λάθος με κασινγκ της παλιάς σελίδας στον σαφάρι, συγνώμη!

2020-04-19 09:10 UTC, jimDragon commented
Συγνώμη για το αργοπορημένο σχόλιο, δεν είχα παρατηρήσει την εξέληξη αυτού του issue... Υπάρχουν μερικά προβλήματα με αυτό το PR κατά την γνώμη μου και του @provopoulos. Πρώτον παρατηρήθηκε οτι πλέον το mobile view στο homepage έχει καταστραφεί καθώς τα κουμπία "Learn more" δεν είναι στις σωστές θέσεις τους. Επιπλέον, υπάρχει άλλο ένα θέμα με την διπλή γραμμή ακριβώς από κάτω από το feature row το οποίο υποψιάζομαι έχέι να κάνει με κάποιο λανθασμένο div nesting. Τέλος με το να υπάρχει το include σε αυτό το αποθετήριο δεν νομίζω οτι  αποτελεί ολοκληρομένη συνεισφορά καθώς είχαμε δώσει ιδιαίτερη έμφαση στο γεγονός οτι έχουμε το minimal-ionio theme σε ξεχωριστό αποθετήριο μαζί με τα includes του και τα συναφή. Αν ο λόγος που συνέβη αυτό βέβαια είναι για να διευκολυνθέι το minimal-ionio upgrade τότε δεκτό αλλά θα πρέπει να ξαναπροσαρμωστεί αμέσως.

Ωστόσο δεν θα ήταν πιο σωστό να ήταν η πιο πρόσφατη ανακοίνωση και όχι κάποια τυχαία;

Ξανά, συγχωρέστε με για το αργοπορημένο σχόλιο αλλά ήθελα να μοιραστώ τις σκέψεις μου και του @provopoulos.

2020-04-20 03:19 UTC, provopoulos commented
For clarity:
[BEFORE](https://user-images.githubusercontent.com/56654653/79710129-b6cc4100-82cc-11ea-9eb9-fb2c3818e2da.png)
[AFTER](https://user-images.githubusercontent.com/56654653/79710393-8638d700-82cd-11ea-8342-5764b7134c32.png)
Επειδή χρειάστηκε να κάνω αλλαγές σε σχετικό issue: https://github.com/ioniodi/site-gr/issues/83#issuecomment-616281340, έχω μεταφέρει το `dynamic.html` στο αποθετήριο του θέματος και οι αλλαγές που έχω κάνει στο `index.html` επιλύουν (νομίζω) το ζήτημα με το `DIV_NESTING` (ευχαριστώ @jimDragon) ωστόσο τα `Learn More` εξακολουθούν να μην εμφανίζονται σωστά.

2020-04-20 03:29 UTC, provopoulos commented
Σε αυτά που είπε ο Δημήτρης θα ήθελα να προσθέσω μια πιθανή μελλοντική βελτίωση. Να υπάρχει κάποιο όριο, πιθανόν, εμφάνισης λέξεων ώστε να μην υπάρχει ασυμφωνία ευθυγράμμισης των στηλών, π.χ. https://sharp-borg-3fc7ea.netlify.com/
Το Twitter module: https://github.com/ioniodi/site-gr/issues/83, έχει συγκεκριμένες (fixed) διαστάσεις `data-width="" data-height=""` οπότε θα ήταν καλό οι υπόλοιπες στήλες να ευθυγραμμίζονται ως προς αυτό κι όχι το αντίθετο.

2020-04-22 08:54 UTC, epidrome commented
@jimDragon μπράβο σου για την αναλυτική περιγραφή, η οποία όμως για να είναι χρήσιμη στο έργο θα πρέπει να σπάσει σε επιμέρους τμήματα τα οποία θα γίνουν νέα θέματα σε συντονισμό με τον @provopoulos που φαίνεται να έχει βρει λύση για κάποια και με ανάθεση σε συντελεστές που θα μπορούσαν να βοηθήσουν

προφανώς δεν έχει νόημα να τα συζητάμε εδώ, γιατί είναι σαν "να κλαίμε πάνω από το χυμένο γάλα", ας δώσουμε λύση καλύτερα!